### ISSUE TITLE
Mandate token breaks scheduled mailing (1.2.3.beta1)

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.sepa#399]
@mielert reports (https://github.com/systopia/de.systopia.donrec/issues/35):

When sending a newsletter the cron job throws an error. The invalid query is probably part of the new implemented token.

```
[debug_info] => SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE contact_id IN () GROUP BY contact_id; [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY contact_id' at line 1]
```

**Comment by systopia** [comment]
@mielert: Similar to your suggestion, I propose this to fix the issue: https://github.com/Project60/org.project60.sepa/commit/aee3cdd490e9976d2fb9c447c29aa91191838686

Could you please install the fixed ``dev_399`` version (https://github.com/Project60/org.project60.sepa/archive/dev_399.zip) and see if it works for you? If so, I'll release a new beta version soon.

And thanks again for hunting down this bug!

**Comment by mielert** [comment]
Error in fix. Has to be "if(count($cids)>0){" not "if(count($contact_id_list)>0){".
@systopia Do you know why $cids can be empty? Why to trigger sepa_civicrm_tokenValues when there are no contacts?
I'll install your zip as soon as my mailing has finished.

**Comment by systopia** [comment]
> @systopia Do you know why $cids can be empty? Why to trigger sepa_civicrm_tokenValues when there are no contacts?

I'm not sure, it might have to do with the way the mail processor works. There might be a point in checking the ``$context`` variable, but that would mean disabling the tokens for mass mailings. 

The resources (like https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_tokenValues and https://civicrm.org/blog/colemanw/create-your-own-tokens-for-fun-and-profit) don't mention the problem. Maybe it's a problem with 4.7.?

**Comment by mielert** [comment]
@systopia Fix is not working.
Still the same error message. No idea why "if (empty($cids)) return;" doesn't work.

```
Jul 21 08:48:05  [info] $backTrace = #0 //sites/all/modules/civicrm/CRM/Core/Error.php(912): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#2 //sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 //sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: syntax error", -2, 16, (Array:2), "SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#4 //sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-2, 16, (Array:2), "SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#5 //sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -2, NULL, NULL, "SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...", "DB_Error", TRUE)
#6 //sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...")
#7 //sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 //sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#9 //sites/all/modules/civicrm/packages/DB/DataObject.php(2438): DB_common->query("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#10 //sites/all/modules/civicrm/packages/DB/DataObject.php(1627): DB_DataObject->_query("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#11 //sites/all/modules/civicrm/CRM/Core/DAO.php(344): DB_DataObject->query("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#12 //sites/all/modules/civicrm/CRM/Core/DAO.php(1278): CRM_Core_DAO->query("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...", TRUE)
#13 //sites/default/files/civicrm/extensions/org.project60.sepa/sepa.php(593): CRM_Core_DAO::executeQuery("SELECT contact_id, MAX(id) AS mandate_id FROM civicrm_sdd_mandate WHERE conta...")
#14 //sites/all/modules/civicrm/CRM/Utils/Hook.php(240): sepa_civicrm_tokenValues((Array:65), "8277", "2863", (Array:0), NULL)
#15 //sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:36), "civicrm_tokenValues", 5, (Array:65), "8277", "2863", (Array:0), NULL, NULL)
#16 //sites/all/modules/civicrm/CRM/Utils/Hook.php(722): CRM_Utils_Hook_DrupalBase->invoke(5, (Array:65), "8277", "2863", (Array:0), NULL, NULL, "civicrm_tokenValues")
#17 //sites/all/modules/civicrm/CRM/Mailing/BAO/Mailing.php(1236): CRM_Utils_Hook::tokenValues((Array:65), "8277", "2863")
#18 //sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(686): CRM_Mailing_BAO_Mailing->compose("2863", "601849", "86d0f0d21c68b828", "8277", "a@x.de", NULL, FALSE, (Array:0), (Array:0), FALSE, NULL, NULL)
#19 //sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(591): CRM_Mailing_BAO_MailingJob->deliverGroup((Array:200), Object(CRM_Mailing_BAO_Mailing), Object(Mail_smtp), "20160720183515", (Array:0))
#20 //sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(192): CRM_Mailing_BAO_MailingJob->deliver(Object(Mail_smtp), NULL)
#21 //sites/all/modules/civicrm/CRM/Mailing/BAO/Mailing.php(2925): CRM_Mailing_BAO_MailingJob::runJobs(NULL, NULL)
#22 //sites/all/modules/civicrm/api/v3/Job.php(317): CRM_Mailing_BAO_Mailing::processQueue()
#23 //sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_job_process_mailing((Array:1))
#24 //sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
#25 //sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("job", "process_mailing", (Array:1), NULL)
#26 //sites/all/modules/civicrm/CRM/Core/JobManager.php(134): civicrm_api("job", "process_mailing", (Array:1))
#27 //sites/all/modules/civicrm/CRM/Core/JobManager.php(79): CRM_Core_JobManager->executeJob(Object(CRM_Core_ScheduledJob))
#28 //sites/all/modules/civicrm/bin/cron.php(42): CRM_Core_JobManager->execute()
#29 {main}
```

**Comment by scardinius** [comment]
Hi, I know that my [fix](https://github.com/scardinius/org.project60.sepa/commit/51183dedaf61b97bc0385bb270d9bee1351bb37d) looks worse but works fine :-)

```php
if (is_array($cids) && count($cids) > 0) {
....
```

**Comment by systopia** [comment]
@scardinius: Thanks. Are you sure this works? Then I'll just use your fix. 

@mielert: Did this work for you?

**Comment by scardinius** [comment]
@systopia Yes, I'm sure.

**Comment by systopia** [comment]
@scardinius: thanks, I'll release a new beta version with your fix tomorrow

**Comment by systopia** [comment]
Ok, I released [1.2.3.beta2](https://github.com/Project60/org.project60.sepa/releases/tag/1.2.3.beta2), but can anyone explain to me, how

```
if (empty($cids)) return;
```
can cause trouble, while
```
if (is_array($cids) && count($cids) > 0) {
  [...]
} else {
  return;
}
```
doesn't? 

The only way I could think of is, if sometimes ``$cids`` is a comma separated list of IDs instead of an array (which the [documentation](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_tokenValues) doesn't support). But in that case...shouldn't we take care of that instead of skipping it?

@scardinius, @mielert: any thoughts?

**Comment by mielert** [comment]
Test with mail logging enabled is running.
I'm trying to log $cids:
```
else {
    file_put_contents ('civiSEPA.log', "\n\rError @ ".date("c").":\n\r".print_r($cids,true)."\n\r", FILE_APPEND | LOCK_EX);
    return;
  }
```

**Comment by mielert** [comment]
@systopia: If $cids just containing a single cid it's not packed in an array. So it's not empty but can't be imploded.

civiSEPA.log:
```
Error @ 2016-08-03T10:08:03+02:00:
8277
Error @ 2016-08-03T10:22:05+02:00:
17388
```

Demo:
```
echo "var: <pre>".print_r(implode(",","var"),true)."</pre>";
// Result: 
// var:
echo "array(var): <pre>".print_r(implode(",",array("var")),true)."</pre>";
// Result: 
// array(var):
// var
echo "array(var,var): <pre>".print_r(implode(",",array("var","var")),true)."</pre>";
// Result:
// array(var,var):
// var,var
```

@scardinius: So I don't think, "(is_array($cids) && count($cids) > 0)" is a good solution because we're loosing contacts. Probably this one is much better:

```
if (!is_array($cids)){
    $cids = array($cids);
}
[...]
```
If we want to cover empty $cids (case hasn't been logged in my testing):
```
if(!empty($cids)){
    if (!is_array($cids)){
        $cids = array($cids);
    }
    [...]
} else {
    return;
}
```

**Comment by systopia** [comment]
Thanks @mielert! I'll create a new version taking this into account.

**Comment by systopia** [comment]
Ok, I created a new fix (still in the ``dev_399`` branch) that should be able to deal with pretty much anything in ``$cids``.

@mielert: Any chance you could verify this fix?

**Comment by mielert** [comment]
@systopia Ok, test is running without logging of "empty($cids) || !is_array($cids)".

**Comment by systopia** [comment]
Great, thanks! I'll create a new beta release later today!

**Comment by mielert** [comment]
@systopia mailing completed. The former skipped contacts got their mail!
