### ISSUE TITLE
error on upgrade to 1508: API (SearchDisplay, save) does not exist

### ISSUE THREAD

**Issue by KiaraGrouwstra** [Project60/org.project60.sepa#656]
upon upgrading this plugin and running the database upgrade, i encounter the following error:
```
[Error: Update org.project60.sepa to version 1508]

Civi\API\Exception\NotImplementedException: "API (SearchDisplay, save) does not exist (join the API team and implement it!)"

#0 /var/www/civi/wp-content/plugins/civicrm/civicrm/api/api.php(71): Civi\API\Request::create("SearchDisplay", "save", (Array:3))
#1 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(317): civicrm_api4("SearchDisplay", "save", (Array:3))
#2 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(201): CRM_Core_ManagedEntities->insertNewEntity((Array:7))
#3 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(167): CRM_Core_ManagedEntities->reconcileEnabledModule("uk.co.vedaconsulting.mosaico")
#4 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(128): CRM_Core_ManagedEntities->reconcileEnabledModules()
#5 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(413): CRM_Core_ManagedEntities->reconcile()
#6 /var/www/civi/wp-content/uploads/civicrm/ext/org.project60.sepa/CRM/Sepa/Upgrader.php(336): CRM_Core_Invoke::rebuildMenuAndCaches()
#7 /var/www/civi/wp-content/uploads/civicrm/ext/org.project60.sepa/CRM/Sepa/Upgrader/Base.php(74): CRM_Sepa_Upgrader->upgrade_1508()
#8 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Queue/Task.php(73): CRM_Sepa_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1508")
#9 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Queue/Runner.php(215): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#10 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Queue/Page/AJAX.php(36): CRM_Queue_Runner->runNext(TRUE)
#11 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Queue/ErrorPolicy.php(89): CRM_Queue_Page_AJAX::{closure}()
#12 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Queue/Page/AJAX.php(38): CRM_Queue_ErrorPolicy->call(Object(Closure))
#13 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(285): CRM_Queue_Page_AJAX::runNext()
#14 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:13))
#15 /var/www/civi/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:4))
#16 /var/www/civi/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke((Array:4))
#17 /var/www/civi/wp-includes/class-wp-hook.php(307): CiviCRM_For_WordPress->invoke("")
#18 /var/www/civi/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters("", (Array:1))
#19 /var/www/civi/wp-includes/plugin.php(476): WP_Hook->do_action((Array:1))
#20 /var/www/civi/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#21 {main}
```

- OS: Linux 5.19.2-arch1-1
- PHP version: 7.4.32
- MariaDB: Ver 15.1 Distrib 10.5.15-MariaDB
- Wordpress: 6.1.0
- CiviCRM: 5.48.0

**Comment by bjendres** [comment]
Thanks for reporting @KiaraGrouwstra. 

I'm not 100% sure, but it looks like line 3 of the stack trace indicates, that the problem happens reconciling 
the mosaico extension (``uk.co.vedaconsulting.mosaico``). So, to me, it looks like this is *triggered* but not *caused* by CiviSEPA - but I'm not 100% sure either.

@KiaraGrouwstra Could you check if the problem goes away when disabling mosaico first?
@jensschuppe What do you think?

**Comment by KiaraGrouwstra** [comment]
my bad, my apologies

**Comment by bjendres** [comment]
> my bad, my apologies!

All good, thanks for reporting anyway.
